# Generated by Django 3.0.6 on 2020-05-23 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_logdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogDetails',
            new_name='LogDetail',
        ),
    ]
